// frontend-web/src/components/Navbar/Navbar.jsx
import { useState, useContext } from 'react';
import { AuthContext } from '../../context/AuthContext';
import { NavLink } from 'react-router-dom';
import { LogOut, LayoutDashboard, CarFront, CalendarPlus, Users, Wrench, CalendarDays, History, CalendarClock, User, Menu, X } from 'lucide-react';
import './Navbar.css';

const Navbar = () => {
  const { user, logout } = useContext(AuthContext);
  const [menuOpen, setMenuOpen] = useState(false);

  if (!user) return null;

  const navLinkClass = ({ isActive }) => `nav-link ${isActive ? 'active' : ''}`;
  const closeMenu = () => setMenuOpen(false);

  return (
    <nav className="navbar">
      <div className="navbar-container">
        <div className="navbar-brand">
          <img src="/logo.png" alt="ControlCar Logo" className="brand-logo-img" />
          <span className="brand-text">ControlCar</span>
          <span className="brand-role">{user.rol.toLowerCase()}</span>
        </div>

        {/* Hamburger button (mobile only) */}
        <button className="hamburger-btn" onClick={() => setMenuOpen(o => !o)} aria-label="Menú">
          {menuOpen ? <X size={22} /> : <Menu size={22} />}
        </button>

        {/* Nav links */}
        <div className={`navbar-links ${menuOpen ? 'mobile-open' : ''}`}>
          {user.rol === 'CLIENTE' && (
            <>
              <NavLink to="/cliente/panel" className={navLinkClass} onClick={closeMenu}><LayoutDashboard size={17} /> Panel</NavLink>
              <NavLink to="/cliente/mis-vehiculos" className={navLinkClass} onClick={closeMenu}><CarFront size={17} /> Vehículos</NavLink>
              <NavLink to="/cliente/mis-citas" className={navLinkClass} onClick={closeMenu}><CalendarClock size={17} /> Mis Citas</NavLink>
              <NavLink to="/cliente/pedir-cita" className={navLinkClass} onClick={closeMenu}><CalendarPlus size={17} /> Pedir Cita</NavLink>
              <NavLink to="/cliente/perfil" className={navLinkClass} onClick={closeMenu}><User size={17} /> Mi Perfil</NavLink>
            </>
          )}

          {user.rol === 'ADMIN' && (
            <>
              <NavLink to="/admin/panel" className={navLinkClass} onClick={closeMenu}><LayoutDashboard size={17} /> Resumen</NavLink>
              <NavLink to="/admin/citas" className={navLinkClass} onClick={closeMenu}><CalendarPlus size={17} /> Citas</NavLink>
              <NavLink to="/admin/calendario" className={navLinkClass} onClick={closeMenu}><CalendarDays size={17} /> Calendario</NavLink>
              <NavLink to="/admin/historial" className={navLinkClass} onClick={closeMenu}><History size={17} /> Historial</NavLink>
              <NavLink to="/admin/clientes" className={navLinkClass} onClick={closeMenu}><Users size={17} /> Clientes</NavLink>
              <NavLink to="/admin/servicios" className={navLinkClass} onClick={closeMenu}><Wrench size={17} /> Servicios</NavLink>
            </>
          )}

          <div className="navbar-user">
            <span className="user-name">{user.nombreCompleto}</span>
            <button onClick={logout} className="logout-btn" title="Cerrar sesión">
              <LogOut size={18} />
            </button>
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;

// frontend-web-new/src/app/shared/components/navbar/navbar.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { LogOut, LayoutDashboard, CarFront, CalendarPlus, Users, Wrench, CalendarDays, History, CalendarClock, User, Menu, X, MapPin, MessageSquare, LucideAngularModule } from 'lucide-angular';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterModule, LucideAngularModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent {
  authService = inject(AuthService);
  user$ = this.authService.currentUser$;
  
  menuOpen = false;

  readonly LogOut = LogOut;
  readonly LayoutDashboard = LayoutDashboard;
  readonly CarFront = CarFront;
  readonly CalendarPlus = CalendarPlus;
  readonly Users = Users;
  readonly Wrench = Wrench;
  readonly CalendarDays = CalendarDays;
  readonly History = History;
  readonly CalendarClock = CalendarClock;
  readonly User = User;
  readonly Menu = Menu;
  readonly X = X;
  readonly MapPin = MapPin;
  readonly MessageSquare = MessageSquare;

  toggleMenu() {
    this.menuOpen = !this.menuOpen;
  }

  closeMenu() {
    this.menuOpen = false;
  }

  logout() {
    this.authService.logout();
  }
}

<nav class="navbar" *ngIf="(user$ | async) as user">
  <div class="navbar-container">
    <div class="navbar-brand" [routerLink]="user.rol === 'ADMIN' ? '/admin/panel' : '/cliente/panel'">
      <img src="assets/logo.png?v=4" alt="ControlCar Logo" class="brand-logo-img" />
      <span class="brand-role">{{ user.rol | lowercase }}</span>
    </div>

    <!-- Hamburger button (mobile only) -->
    <button class="hamburger-btn" (click)="toggleMenu()" aria-label="Menú">
      <lucide-icon *ngIf="menuOpen" [img]="X" [size]="22"></lucide-icon>
      <lucide-icon *ngIf="!menuOpen" [img]="Menu" [size]="22"></lucide-icon>
    </button>

    <!-- Nav links -->
    <div class="navbar-links" [class.mobile-open]="menuOpen">
      
      <ng-container *ngIf="user.rol === 'CLIENTE'">
        <a routerLink="/cliente/panel" routerLinkActive="active" class="nav-link" (click)="closeMenu()">
          <lucide-icon [img]="LayoutDashboard" [size]="17"></lucide-icon> Panel
        </a>
        <a routerLink="/cliente/mis-vehiculos" routerLinkActive="active" class="nav-link" (click)="closeMenu()">
          <lucide-icon [img]="CarFront" [size]="17"></lucide-icon> Vehículos
        </a>
        <a routerLink="/cliente/mis-citas" routerLinkActive="active" class="nav-link" (click)="closeMenu()">
          <lucide-icon [img]="CalendarClock" [size]="17"></lucide-icon> Mis Citas
        </a>
        <a routerLink="/cliente/pedir-cita" routerLinkActive="active" class="nav-link" (click)="closeMenu()">
          <lucide-icon [img]="CalendarPlus" [size]="17"></lucide-icon> Pedir Cita
        </a>
        <a routerLink="/cliente/perfil" routerLinkActive="active" class="nav-link" (click)="closeMenu()">
          <lucide-icon [img]="User" [size]="17"></lucide-icon> Mi Perfil
        </a>
        <a [routerLink]="['/cliente/panel']" fragment="ubicacion" class="nav-link" (click)="closeMenu()">
          <lucide-icon [img]="MapPin" [size]="17"></lucide-icon> Ubícanos
        </a>
        <a [routerLink]="['/cliente/panel']" fragment="contacto" class="nav-link" (click)="closeMenu()">
          <lucide-icon [img]="MessageSquare" [size]="17"></lucide-icon> Contacto
        </a>
      </ng-container>

      <ng-container *ngIf="user.rol === 'ADMIN'">
        <a routerLink="/admin/panel" routerLinkActive="active" class="nav-link" (click)="closeMenu()">
          <lucide-icon [img]="LayoutDashboard" [size]="17"></lucide-icon> Resumen
        </a>
        <a routerLink="/admin/citas" routerLinkActive="active" class="nav-link" (click)="closeMenu()">
          <lucide-icon [img]="CalendarPlus" [size]="17"></lucide-icon> Citas
        </a>
        <a routerLink="/admin/calendario" routerLinkActive="active" class="nav-link" (click)="closeMenu()">
          <lucide-icon [img]="CalendarDays" [size]="17"></lucide-icon> Calendario
        </a>
        <a routerLink="/admin/historial" routerLinkActive="active" class="nav-link" (click)="closeMenu()">
          <lucide-icon [img]="History" [size]="17"></lucide-icon> Historial
        </a>
        <a routerLink="/admin/clientes" routerLinkActive="active" class="nav-link" (click)="closeMenu()">
          <lucide-icon [img]="Users" [size]="17"></lucide-icon> Clientes
        </a>
        <a routerLink="/admin/servicios" routerLinkActive="active" class="nav-link" (click)="closeMenu()">
          <lucide-icon [img]="Wrench" [size]="17"></lucide-icon> Servicios
        </a>
        <a [routerLink]="['/admin/panel']" fragment="ubicacion" class="nav-link" (click)="closeMenu()">
          <lucide-icon [img]="MapPin" [size]="17"></lucide-icon> Ubícanos
        </a>
      </ng-container>

    </div>

    <!-- Usuario y Logout alineados a la derecha de forma independiente -->
    <div class="navbar-user" [class.mobile-open]="menuOpen">
      <span class="user-name">{{ user.nombreCompleto }}</span>
      <button (click)="logout()" class="logout-btn" title="Cerrar sesión" style="flex-shrink: 0; min-width: 38px;">
        <lucide-icon [img]="LogOut" [size]="18"></lucide-icon>
      </button>
    </div>
  </div>
</nav>
