// frontend-web-new/src/app/features/admin/components/gestion-servicios/gestion-servicios.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { environment } from '../../../../../environments/environment';
import { PageHeaderComponent } from '../../../../shared/components/page-header/page-header.component';
import { Wrench, Plus, Pencil, Trash2, Clock, Euro, LucideAngularModule } from 'lucide-angular';

@Component({
  selector: 'app-gestion-servicios',
  standalone: true,
  imports: [CommonModule, FormsModule, PageHeaderComponent, LucideAngularModule],
  templateUrl: './gestion-servicios.component.html'
})
export class GestionServiciosComponent implements OnInit {
  private http = inject(HttpClient);

  servicios: any[] = [];
  loading = true;
  showForm = false;
  editando: any = null;
  form = { nombre: '', descripcion: '', precio: 0, duracionMinutos: 60 };

  readonly Wrench = Wrench;
  readonly Plus = Plus;
  readonly Pencil = Pencil;
  readonly Trash2 = Trash2;
  readonly Clock = Clock;
  readonly Euro = Euro;

  ngOnInit() {
    this.fetchServicios();
  }

  fetchServicios() {
    this.loading = true;
    this.http.get<any[]>(`${environment.apiUrl}/admin/servicios`).subscribe({
      next: (res) => {
        this.servicios = res;
        this.loading = false;
      },
      error: () => this.loading = false
    });
  }

  openCreate() {
    this.editando = null;
    this.form = { nombre: '', descripcion: '', precio: 0, duracionMinutos: 60 };
    this.showForm = true;
  }

  openEdit(s: any) {
    this.editando = s;
    this.form = { nombre: s.nombre, descripcion: s.descripcion || '', precio: s.precio || 0, duracionMinutos: s.duracionMinutos || 60 };
    this.showForm = true;
  }

  closeForm() {
    this.showForm = false;
    this.editando = null;
  }

  handleSubmit() {
    const payload = { ...this.form };
    
    if (this.editando) {
      this.http.put(`${environment.apiUrl}/admin/servicios/${this.editando.id}`, payload).subscribe({
        next: () => {
          this.closeForm();
          this.fetchServicios();
        },
        error: () => alert('Error al actualizar')
      });
    } else {
      this.http.post(`${environment.apiUrl}/admin/servicios`, payload).subscribe({
        next: () => {
          this.closeForm();
          this.fetchServicios();
        },
        error: () => alert('Error al crear')
      });
    }
  }

  handleEliminar(id: number) {
    if (!window.confirm('¿Seguro que quieres eliminar este servicio?')) return;
    this.http.delete(`${environment.apiUrl}/admin/servicios/${id}`).subscribe({
      next: () => this.fetchServicios(),
      error: () => alert('Error al eliminar')
    });
  }
}

<div *ngIf="loading" style="padding: 2rem; color: var(--text-muted);">Cargando servicios...</div>

<div *ngIf="!loading">
  <app-page-header title="Gestión de Servicios" subtitle="Crea, edita y administra los servicios ofrecidos en el taller."></app-page-header>
  
  <div *ngIf="!showForm" style="margin-top: -2.5rem; margin-bottom: 2rem; display: flex; justify-content: flex-end;">
    <button (click)="openCreate()" class="btn btn-primary" style="display: flex; align-items: center; gap: 0.4rem;">
      <lucide-icon [img]="Plus" [size]="17"></lucide-icon> Nuevo Servicio
    </button>
  </div>

  <div *ngIf="showForm" class="card" style="margin-bottom: 2rem; border-left: 3px solid var(--primary); box-shadow: var(--shadow-glow-red);">
    <h3 style="margin-bottom: 1.25rem; font-size: 1.05rem;">{{ editando ? '✏️ Editar Servicio' : '➕ Nuevo Servicio' }}</h3>
    <form (ngSubmit)="handleSubmit()" style="display: grid; grid-template-columns: 1fr 1fr; gap: 1rem;">
      <div class="form-group" style="grid-column: 1 / -1;">
        <label class="form-label">Nombre del Servicio *</label>
        <input required class="form-input" name="nombre" [(ngModel)]="form.nombre" placeholder="Ej: Cambio de aceite" />
      </div>
      <div class="form-group" style="grid-column: 1 / -1;">
        <label class="form-label">Descripción</label>
        <textarea class="form-input" name="descripcion" [(ngModel)]="form.descripcion" placeholder="Descripción del servicio..." style="resize: vertical; min-height: 70px;"></textarea>
      </div>
      <div class="form-group">
        <label class="form-label">Precio (€) *</label>
        <input required type="number" step="0.01" min="0" class="form-input" name="precio" [(ngModel)]="form.precio" placeholder="Ej: 45.00" />
      </div>
      <div class="form-group">
        <label class="form-label">Duración (minutos) *</label>
        <input required type="number" min="15" step="15" class="form-input" name="duracionMinutos" [(ngModel)]="form.duracionMinutos" />
      </div>
      <div style="grid-column: 1 / -1; display: flex; gap: 1rem; justify-content: flex-end;">
        <button type="button" class="btn btn-outline" (click)="closeForm()">Cancelar</button>
        <button type="submit" class="btn btn-primary">{{ editando ? 'Guardar Cambios' : 'Crear Servicio' }}</button>
      </div>
    </form>
  </div>

  <div *ngIf="servicios.length === 0 && !showForm" class="card" style="text-align: center; padding: 3rem;">
    <lucide-icon [img]="Wrench" [size]="48" style="color: var(--text-muted); margin: 0 auto 1rem; opacity: 0.4;"></lucide-icon>
    <p>No hay servicios configurados. Crea el primero.</p>
  </div>

  <div *ngIf="servicios.length > 0" style="display: flex; flex-direction: column; gap: 1rem;">
    <div *ngFor="let s of servicios" class="card" style="display: flex; align-items: center; gap: 1.5rem; flex-wrap: wrap;">
      <div style="flex: 1;">
        <h3 style="margin: 0 0 0.25rem 0; font-size: 1.05rem;">{{ s.nombre }}</h3>
        <p *ngIf="s.descripcion" style="margin: 0 0 0.5rem 0; font-size: 0.85rem; color: var(--text-muted);">{{ s.descripcion }}</p>
        <div style="display: flex; gap: 1rem; flex-wrap: wrap;">
          <span style="display: flex; align-items: center; gap: 0.3rem; font-size: 0.85rem; color: var(--secondary); font-weight: 700;">
            <lucide-icon [img]="Euro" [size]="14"></lucide-icon> {{ s.precio ?? '—' }}€
          </span>
          <span style="display: flex; align-items: center; gap: 0.3rem; font-size: 0.85rem; color: var(--text-muted);">
            <lucide-icon [img]="Clock" [size]="14"></lucide-icon> {{ s.duracionMinutos }} min
          </span>
        </div>
      </div>
      <div style="display: flex; gap: 0.5rem; flex-shrink: 0;">
        <button class="btn btn-outline" (click)="openEdit(s)" style="padding: 0.5rem 0.85rem; display: flex; align-items: center; gap: 0.3rem; font-size: 0.83rem;">
          <lucide-icon [img]="Pencil" [size]="14"></lucide-icon> Editar
        </button>
        <button class="btn btn-danger" (click)="handleEliminar(s.id)" style="padding: 0.5rem 0.85rem; display: flex; align-items: center; gap: 0.3rem; font-size: 0.83rem;">
          <lucide-icon [img]="Trash2" [size]="14"></lucide-icon> Eliminar
        </button>
      </div>
    </div>
  </div>
</div>

// frontend-web/src/pages/admin/GestionServicios.jsx
import { useState, useEffect } from 'react';
import api from '../../api/axiosConfig';
import { Wrench, Plus, Pencil, Trash2, Clock, Euro } from 'lucide-react';
import PageHeader from '../../components/PageHeader/PageHeader';
import { useToast } from '../../components/Toast/Toast';
import { SkeletonList } from '../../components/Skeleton/Skeleton';

const EMPTY = { nombre: '', descripcion: '', precio: '', duracionMinutos: 60 };

const GestionServicios = () => {
  const [servicios, setServicios] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [editando, setEditando] = useState(null); // null = crear, obj = editar
  const [form, setForm] = useState(EMPTY);
  const toast = useToast();

  const fetchServicios = async () => {
    try {
      const res = await api.get('/admin/servicios');
      setServicios(res.data);
    } catch {
      toast('Error cargando servicios', 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchServicios(); }, []);

  const openCreate = () => { setEditando(null); setForm(EMPTY); setShowForm(true); };
  const openEdit = (s) => { setEditando(s); setForm({ nombre: s.nombre, descripcion: s.descripcion || '', precio: s.precio || '', duracionMinutos: s.duracionMinutos || 60 }); setShowForm(true); };
  const closeForm = () => { setShowForm(false); setEditando(null); setForm(EMPTY); };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const payload = { ...form, precio: parseFloat(form.precio), duracionMinutos: parseInt(form.duracionMinutos) };
    try {
      if (editando) {
        await api.put(`/admin/servicios/${editando.id}`, payload);
        toast('Servicio actualizado correctamente', 'success');
      } else {
        await api.post('/admin/servicios', payload);
        toast('Servicio creado correctamente', 'success');
      }
      closeForm();
      fetchServicios();
    } catch {
      toast('Error al guardar el servicio', 'error');
    }
  };

  const handleEliminar = async (id) => {
    if (!window.confirm('¿Seguro que quieres eliminar este servicio?')) return;
    try {
      await api.delete(`/admin/servicios/${id}`);
      toast('Servicio eliminado', 'info');
      fetchServicios();
    } catch {
      toast('Error al eliminar el servicio', 'error');
    }
  };

  return (
    <div>
      <PageHeader
        icon={<Wrench size={26} color="var(--primary)" />}
        title="Gestión de Servicios"
        subtitle="Crea, edita y administra los servicios ofrecidos en el taller."
        action={!showForm && (
          <button className="btn btn-primary" onClick={openCreate} style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
            <Plus size={17} /> Nuevo Servicio
          </button>
        )}
      />

      {showForm && (
        <div className="card" style={{ marginBottom: '2rem', borderLeft: '3px solid var(--primary)', boxShadow: 'var(--shadow-glow-red)' }}>
          <h3 style={{ marginBottom: '1.25rem', fontSize: '1.05rem' }}>{editando ? '✏️ Editar Servicio' : '➕ Nuevo Servicio'}</h3>
          <form onSubmit={handleSubmit} style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
            <div className="form-group" style={{ gridColumn: '1 / -1' }}>
              <label className="form-label">Nombre del Servicio *</label>
              <input required className="form-input" value={form.nombre} onChange={e => setForm({...form, nombre: e.target.value})} placeholder="Ej: Cambio de aceite" />
            </div>
            <div className="form-group" style={{ gridColumn: '1 / -1' }}>
              <label className="form-label">Descripción</label>
              <textarea className="form-input" value={form.descripcion} onChange={e => setForm({...form, descripcion: e.target.value})} placeholder="Descripción del servicio..." style={{ resize: 'vertical', minHeight: '70px' }} />
            </div>
            <div className="form-group">
              <label className="form-label">Precio (€) *</label>
              <input required type="number" step="0.01" min="0" className="form-input" value={form.precio} onChange={e => setForm({...form, precio: e.target.value})} placeholder="Ej: 45.00" />
            </div>
            <div className="form-group">
              <label className="form-label">Duración (minutos) *</label>
              <input required type="number" min="15" step="15" className="form-input" value={form.duracionMinutos} onChange={e => setForm({...form, duracionMinutos: e.target.value})} />
            </div>
            <div style={{ gridColumn: '1 / -1', display: 'flex', gap: '1rem', justifyContent: 'flex-end' }}>
              <button type="button" className="btn btn-outline" onClick={closeForm}>Cancelar</button>
              <button type="submit" className="btn btn-primary">{editando ? 'Guardar Cambios' : 'Crear Servicio'}</button>
            </div>
          </form>
        </div>
      )}

      {loading ? (
        <SkeletonList rows={4} />
      ) : servicios.length === 0 ? (
        <div className="card" style={{ textAlign: 'center', padding: '3rem' }}>
          <Wrench size={48} color="var(--text-muted)" style={{ margin: '0 auto 1rem', opacity: 0.4 }} />
          <p>No hay servicios configurados. Crea el primero.</p>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          {servicios.map(s => (
            <div key={s.id} className="card" style={{ display: 'flex', alignItems: 'center', gap: '1.5rem', flexWrap: 'wrap' }}>
              <div style={{ flex: 1 }}>
                <h3 style={{ margin: '0 0 0.25rem 0', fontSize: '1.05rem' }}>{s.nombre}</h3>
                {s.descripcion && <p style={{ margin: '0 0 0.5rem 0', fontSize: '0.85rem', color: 'var(--text-muted)' }}>{s.descripcion}</p>}
                <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
                  <span style={{ display: 'flex', alignItems: 'center', gap: '0.3rem', fontSize: '0.85rem', color: 'var(--secondary)', fontWeight: 700 }}>
                    <Euro size={14} /> {s.precio ?? '—'}€
                  </span>
                  <span style={{ display: 'flex', alignItems: 'center', gap: '0.3rem', fontSize: '0.85rem', color: 'var(--text-muted)' }}>
                    <Clock size={14} /> {s.duracionMinutos} min
                  </span>
                </div>
              </div>
              <div style={{ display: 'flex', gap: '0.5rem', flexShrink: 0 }}>
                <button className="btn btn-outline" onClick={() => openEdit(s)} style={{ padding: '0.5rem 0.85rem', display: 'flex', alignItems: 'center', gap: '0.3rem', fontSize: '0.83rem' }}>
                  <Pencil size={14} /> Editar
                </button>
                <button className="btn btn-danger" onClick={() => handleEliminar(s.id)} style={{ padding: '0.5rem 0.85rem', display: 'flex', alignItems: 'center', gap: '0.3rem', fontSize: '0.83rem' }}>
                  <Trash2 size={14} /> Eliminar
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default GestionServicios;
