// frontend-web/src/pages/cliente/MisCitas.jsx
import { useState, useEffect } from 'react';
import api from '../../api/axiosConfig';
import { CalendarClock, XCircle, Clock, CheckCircle2, Ban } from 'lucide-react';
import PageHeader from '../../components/PageHeader/PageHeader';
import { useToast } from '../../components/Toast/Toast';
import { SkeletonList } from '../../components/Skeleton/Skeleton';

const ESTADO_STYLES = {
  PENDIENTE:  { color: '#fcd34d', bg: 'rgba(245,158,11,0.1)',  border: 'rgba(245,158,11,0.3)',  icon: <Clock size={14}/> },
  CONFIRMADA: { color: '#93c5fd', bg: 'rgba(59,130,246,0.1)',  border: 'rgba(59,130,246,0.3)',  icon: <CheckCircle2 size={14}/> },
  EN_CURSO:   { color: '#d8b4fe', bg: 'rgba(168,85,247,0.1)',  border: 'rgba(168,85,247,0.3)',  icon: <Clock size={14}/> },
  FINALIZADA: { color: '#6ee7b7', bg: 'rgba(16,185,129,0.1)',  border: 'rgba(16,185,129,0.3)',  icon: <CheckCircle2 size={14}/> },
  CANCELADA:  { color: '#fca5a5', bg: 'rgba(239,68,68,0.1)',   border: 'rgba(239,68,68,0.3)',   icon: <Ban size={14}/> },
};

const MisCitas = () => {
  const [citas, setCitas] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filtro, setFiltro] = useState('activas'); // 'activas' | 'historial' | 'todas'
  const toast = useToast();

  const fetchCitas = async () => {
    try {
      const res = await api.get('/cliente/citas');
      setCitas(res.data);
    } catch {
      toast('Error cargando tus citas', 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchCitas(); }, []);

  const handleCancelar = async (id) => {
    if (!window.confirm('¿Seguro que quieres cancelar esta cita?')) return;
    try {
      await api.put(`/cliente/citas/${id}/cancelar`);
      toast('Cita cancelada correctamente', 'info');
      fetchCitas();
    } catch {
      toast('No se pudo cancelar la cita', 'error');
    }
  };

  const ACTIVOS = ['PENDIENTE', 'CONFIRMADA', 'EN_CURSO'];
  const HISTORIAL = ['FINALIZADA', 'CANCELADA'];

  const citasFiltradas = citas.filter(c => {
    if (filtro === 'activas')   return ACTIVOS.includes(c.estado);
    if (filtro === 'historial') return HISTORIAL.includes(c.estado);
    return true;
  });

  return (
    <div>
      <PageHeader
        icon={<CalendarClock size={26} color="var(--primary)" />}
        title="Mis Citas"
        subtitle="Consulta todas tus reservas activas y tu historial de visitas."
      />

      {/* Filtro tabs */}
      <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '1.5rem' }}>
        {[
          { key: 'activas', label: '📅 Activas' },
          { key: 'historial', label: '📋 Historial' },
          { key: 'todas', label: '🔍 Todas' },
        ].map(tab => (
          <button
            key={tab.key}
            onClick={() => setFiltro(tab.key)}
            style={{
              padding: '0.5rem 1.1rem',
              borderRadius: '20px',
              border: `1px solid ${filtro === tab.key ? 'var(--primary)' : 'var(--border-color)'}`,
              background: filtro === tab.key ? 'rgba(225,29,72,0.12)' : 'transparent',
              color: filtro === tab.key ? 'var(--primary)' : 'var(--text-muted)',
              fontWeight: filtro === tab.key ? 700 : 400,
              cursor: 'pointer',
              fontSize: '0.875rem',
              transition: 'all 0.2s',
              fontFamily: "'Outfit', sans-serif",
            }}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {loading ? <SkeletonList rows={3} /> : citasFiltradas.length === 0 ? (
        <div className="card" style={{ textAlign: 'center', padding: '3rem' }}>
          <CalendarClock size={48} color="var(--text-muted)" style={{ margin: '0 auto 1rem', opacity: 0.4 }} />
          <p>No hay citas en esta categoría.</p>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          {citasFiltradas.map(cita => {
            const st = ESTADO_STYLES[cita.estado] || ESTADO_STYLES.PENDIENTE;
            const esCancelable = ACTIVOS.includes(cita.estado);
            return (
              <div key={cita.id} className="card" style={{ display: 'flex', alignItems: 'flex-start', gap: '1.25rem', flexWrap: 'wrap' }}>
                {/* Bloque de Fecha */}
                <div style={{ textAlign: 'center', background: 'var(--bg-main)', border: '1px solid var(--border-color)', padding: '0.75rem', borderRadius: '10px', minWidth: '68px', flexShrink: 0 }}>
                  <span style={{ display: 'block', fontSize: '1.5rem', fontWeight: 900, color: 'var(--primary)', lineHeight: 1 }}>
                    {new Date(cita.fechaHora).getDate()}
                  </span>
                  <span style={{ display: 'block', fontSize: '0.7rem', color: 'var(--text-muted)', textTransform: 'uppercase', fontWeight: 600 }}>
                    {new Date(cita.fechaHora).toLocaleString('es-ES', { month: 'short' })}
                  </span>
                  <div style={{ marginTop: '0.35rem', paddingTop: '0.35rem', borderTop: '1px dashed var(--border-color)', fontSize: '0.75rem', fontWeight: 700, color: 'var(--text-main)' }}>
                    {new Date(cita.fechaHora).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </div>
                </div>

                {/* Info */}
                <div style={{ flex: 1 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.4rem', flexWrap: 'wrap' }}>
                    <h3 style={{ margin: 0, fontSize: '1rem' }}>{cita.servicio?.nombre}</h3>
                    <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.3rem', padding: '2px 10px', borderRadius: '12px', background: st.bg, border: `1px solid ${st.border}`, color: st.color, fontSize: '0.72rem', fontWeight: 700, textTransform: 'uppercase' }}>
                      {st.icon} {cita.estado.replace('_', ' ')}
                    </span>
                  </div>
                  <p style={{ margin: '0', fontSize: '0.875rem', color: 'var(--text-muted)' }}>
                    🚗 {cita.vehiculo?.marca} {cita.vehiculo?.modelo}
                    <span style={{ fontFamily: 'monospace', background: 'rgba(255,255,255,0.05)', padding: '1px 5px', borderRadius: '4px', marginLeft: '6px', border: '1px solid var(--border-color)', fontSize: '0.8rem' }}>{cita.vehiculo?.matricula}</span>
                  </p>
                </div>

                {/* Acción cancelar */}
                {esCancelable && (
                  <button
                    onClick={() => handleCancelar(cita.id)}
                    className="btn btn-danger"
                    style={{ padding: '0.5rem 0.9rem', display: 'flex', alignItems: 'center', gap: '0.3rem', fontSize: '0.82rem', flexShrink: 0 }}
                  >
                    <XCircle size={15} /> Cancelar
                  </button>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default MisCitas;

// frontend-web-new/src/app/features/cliente/components/mis-citas/mis-citas.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../../../environments/environment';
import { PageHeaderComponent } from '../../../../shared/components/page-header/page-header.component';
import { CalendarClock, XCircle, Clock, CheckCircle2, Ban, LucideAngularModule } from 'lucide-angular';

@Component({
  selector: 'app-mis-citas',
  standalone: true,
  imports: [CommonModule, PageHeaderComponent, LucideAngularModule],
  templateUrl: './mis-citas.component.html'
})
export class MisCitasComponent implements OnInit {
  private http = inject(HttpClient);

  citas: any[] = [];
  loading = true;
  filtro = 'activas';

  readonly CalendarClock = CalendarClock;
  readonly XCircle = XCircle;
  readonly Clock = Clock;
  readonly CheckCircle2 = CheckCircle2;
  readonly Ban = Ban;

  ESTADO_STYLES: any = {
    PENDIENTE:  { color: '#fcd34d', bg: 'rgba(245,158,11,0.1)',  border: 'rgba(245,158,11,0.3)',  iconName: 'Clock' },
    CONFIRMADA: { color: '#93c5fd', bg: 'rgba(59,130,246,0.1)',  border: 'rgba(59,130,246,0.3)',  iconName: 'CheckCircle2' },
    EN_CURSO:   { color: '#d8b4fe', bg: 'rgba(168,85,247,0.1)',  border: 'rgba(168,85,247,0.3)',  iconName: 'Clock' },
    FINALIZADA: { color: '#6ee7b7', bg: 'rgba(16,185,129,0.1)',  border: 'rgba(16,185,129,0.3)',  iconName: 'CheckCircle2' },
    CANCELADA:  { color: '#fca5a5', bg: 'rgba(239,68,68,0.1)',   border: 'rgba(239,68,68,0.3)',   iconName: 'Ban' }
  };

  ACTIVOS = ['PENDIENTE', 'CONFIRMADA', 'EN_CURSO'];
  HISTORIAL = ['FINALIZADA', 'CANCELADA'];

  ngOnInit() {
    this.fetchCitas();
  }

  fetchCitas() {
    this.loading = true;
    this.http.get<any[]>(`${environment.apiUrl}/cliente/citas`).subscribe({
      next: (res) => {
        this.citas = res;
        this.loading = false;
      },
      error: () => this.loading = false
    });
  }

  setFiltro(val: string) {
    this.filtro = val;
  }

  get citasFiltradas() {
    return this.citas.filter(c => {
      if (this.filtro === 'activas') return this.ACTIVOS.includes(c.estado);
      if (this.filtro === 'historial') return this.HISTORIAL.includes(c.estado);
      return true;
    });
  }

  handleCancelar(id: number) {
    if (!window.confirm('¿Seguro que quieres cancelar esta cita?')) return;
    this.http.put(`${environment.apiUrl}/cliente/citas/${id}/cancelar`, {}).subscribe({
      next: () => {
        alert('Cita cancelada correctamente');
        this.fetchCitas();
      },
      error: () => alert('No se pudo cancelar la cita')
    });
  }

  getIconForEstado(estado: string) {
      if(estado === 'PENDIENTE' || estado === 'EN_CURSO') return this.Clock;
      if(estado === 'CONFIRMADA' || estado === 'FINALIZADA') return this.CheckCircle2;
      if(estado === 'CANCELADA') return this.Ban;
      return this.Clock;
  }
}

<div>
  <app-page-header title="Mis Citas" subtitle="Consulta todas tus reservas activas y tu historial de visitas."></app-page-header>

  <!-- Filtro tabs -->
  <div style="display: flex; gap: 0.5rem; margin-bottom: 1.5rem;">
    <button (click)="setFiltro('activas')" [ngStyle]="{'background': filtro === 'activas' ? 'rgba(225,29,72,0.12)' : 'transparent', 'color': filtro === 'activas' ? 'var(--primary)' : 'var(--text-muted)', 'border': filtro === 'activas' ? '1px solid var(--primary)' : '1px solid var(--border-color)'}" style="padding: 0.5rem 1.1rem; border-radius: 20px; font-weight: 700; cursor: pointer; font-size: 0.875rem; transition: all 0.2s; font-family: 'Outfit', sans-serif;">
      📅 Activas
    </button>
    <button (click)="setFiltro('historial')" [ngStyle]="{'background': filtro === 'historial' ? 'rgba(225,29,72,0.12)' : 'transparent', 'color': filtro === 'historial' ? 'var(--primary)' : 'var(--text-muted)', 'border': filtro === 'historial' ? '1px solid var(--primary)' : '1px solid var(--border-color)'}" style="padding: 0.5rem 1.1rem; border-radius: 20px; cursor: pointer; font-size: 0.875rem; transition: all 0.2s; font-family: 'Outfit', sans-serif;">
      📋 Historial
    </button>
    <button (click)="setFiltro('todas')" [ngStyle]="{'background': filtro === 'todas' ? 'rgba(225,29,72,0.12)' : 'transparent', 'color': filtro === 'todas' ? 'var(--primary)' : 'var(--text-muted)', 'border': filtro === 'todas' ? '1px solid var(--primary)' : '1px solid var(--border-color)'}" style="padding: 0.5rem 1.1rem; border-radius: 20px; cursor: pointer; font-size: 0.875rem; transition: all 0.2s; font-family: 'Outfit', sans-serif;">
      🔍 Todas
    </button>
  </div>

  <div *ngIf="loading" style="padding: 2rem; color: var(--text-muted);">Cargando citas...</div>

  <div *ngIf="!loading && citasFiltradas.length === 0" class="card" style="text-align: center; padding: 3rem;">
    <lucide-icon [img]="CalendarClock" [size]="48" style="color: var(--text-muted); margin: 0 auto 1rem; opacity: 0.4;"></lucide-icon>
    <p>No hay citas en esta categoría.</p>
  </div>

  <div *ngIf="!loading && citasFiltradas.length > 0" style="display: flex; flex-direction: column; gap: 1rem;">
    <div *ngFor="let cita of citasFiltradas" class="card" style="display: flex; align-items: flex-start; gap: 1.25rem; flex-wrap: wrap;">
      
      <!-- Bloque de Fecha -->
      <div style="text-align: center; background: var(--bg-main); border: 1px solid var(--border-color); padding: 0.75rem; border-radius: 10px; min-width: 68px; flex-shrink: 0;">
        <span style="display: block; font-size: 1.5rem; font-weight: 900; color: var(--primary); line-height: 1;">
          {{ cita.fechaHora | date:'d' }}
        </span>
        <span style="display: block; font-size: 0.7rem; color: var(--text-muted); text-transform: uppercase; font-weight: 600;">
          {{ cita.fechaHora | date:'MMM' }}
        </span>
        <div style="margin-top: 0.35rem; padding-top: 0.35rem; border-top: 1px dashed var(--border-color); font-size: 0.75rem; font-weight: 700; color: var(--text-main);">
          {{ cita.fechaHora | date:'shortTime' }}
        </div>
      </div>

      <!-- Info -->
      <div style="flex: 1;">
        <div style="display: flex; align-items: center; gap: 0.75rem; margin-bottom: 0.4rem; flex-wrap: wrap;">
          <h3 style="margin: 0; font-size: 1rem;">{{ cita.servicio?.nombre }}</h3>
          <span [ngStyle]="{'background': ESTADO_STYLES[cita.estado]?.bg, 'border': '1px solid ' + ESTADO_STYLES[cita.estado]?.border, 'color': ESTADO_STYLES[cita.estado]?.color}" style="display: inline-flex; align-items: center; gap: 0.3rem; padding: 2px 10px; border-radius: 12px; font-size: 0.72rem; font-weight: 700; text-transform: uppercase;">
            <lucide-icon [img]="getIconForEstado(cita.estado)" [size]="14"></lucide-icon> {{ cita.estado.replace('_', ' ') }}
          </span>
        </div>
        <p style="margin: 0; font-size: 0.875rem; color: var(--text-muted);">
          🚗 {{ cita.vehiculo?.marca }} {{ cita.vehiculo?.modelo }}
          <span style="font-family: monospace; background: rgba(255,255,255,0.05); padding: 1px 5px; border-radius: 4px; margin-left: 6px; border: 1px solid var(--border-color); font-size: 0.8rem;">{{ cita.vehiculo?.matricula }}</span>
        </p>
      </div>

      <!-- Acción cancelar -->
      <button *ngIf="ACTIVOS.includes(cita.estado)" (click)="handleCancelar(cita.id)" class="btn btn-danger" style="padding: 0.5rem 0.9rem; display: flex; align-items: center; gap: 0.3rem; font-size: 0.82rem; flex-shrink: 0;">
        <lucide-icon [img]="XCircle" [size]="15"></lucide-icon> Cancelar
      </button>

    </div>
  </div>
</div>
