// frontend-web/src/pages/cliente/ClientePanel.jsx
import { useState, useEffect, useContext } from 'react';
import { AuthContext } from '../../context/AuthContext';
import api from '../../api/axiosConfig';
import { CalendarClock, Car, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import PageHeader from '../../components/PageHeader/PageHeader';

const ClientePanel = () => {
  const { user } = useContext(AuthContext);
  const [citas, setCitas] = useState([]);
  const [vehiculos, setVehiculos] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchDashboardData = async () => {
      try {
        const [citasRes, vehiculosRes] = await Promise.all([
          api.get('/cliente/citas'),
          api.get('/cliente/vehiculos')
        ]);
        setCitas(citasRes.data);
        setVehiculos(vehiculosRes.data);
      } catch (error) {
        console.error("Error fetching dashboard data:", error);
      } finally {
        setLoading(false);
      }
    };
    fetchDashboardData();
  }, []);

  if (loading) return <div style={{ padding: '2rem', color: 'var(--text-muted)' }}>Cargando panel...</div>;

  const proximasCitas = citas.filter(c => c.estado === 'PENDIENTE' || c.estado === 'EN_CURSO');

  return (
    <div>
      <PageHeader
        icon={<CalendarClock size={26} color="var(--primary)" />}
        title={`Hola, ${user?.nombreCompleto} 👋`}
        subtitle="Bienvenido a tu panel de control. Gestiona tu garaje y tus próximas visitas."
      />

      <div className="grid-2">
        {/* Tarjeta de Próxima Cita */}
        <div className="card" style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <h2 style={{ fontSize: '1.1rem', display: 'flex', alignItems: 'center', gap: '0.5rem', margin: 0 }}>
              <CalendarClock size={20} color="var(--primary)"/> Próximas Citas
            </h2>
            <Link to="/cliente/pedir-cita" className="btn btn-outline" style={{ fontSize: '0.72rem', padding: '0.35rem 0.85rem' }}>
              + Nueva Cita
            </Link>
          </div>

          {proximasCitas.length > 0 ? (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              {proximasCitas.slice(0, 3).map(cita => (
                <div key={cita.id} style={{ padding: '1rem', border: '1px solid var(--border-color)', borderRadius: '10px', background: 'var(--bg-main)', transition: 'border-color 0.2s' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.35rem' }}>
                    <strong style={{ fontSize: '0.9rem' }}>{new Date(cita.fechaHora).toLocaleDateString()} a las {new Date(cita.fechaHora).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}</strong>
                    <span className={`badge ${cita.estado}`}>{cita.estado.replace('_', ' ')}</span>
                  </div>
                  <p style={{ margin: 0, fontSize: '0.85rem', color: 'var(--text-muted)' }}>
                    {cita.servicio?.nombre} — {cita.vehiculo?.marca} {cita.vehiculo?.modelo} ({cita.vehiculo?.matricula})
                  </p>
                </div>
              ))}
            </div>
          ) : (
            <div style={{ padding: '2rem 1rem', textAlign: 'center', background: 'var(--bg-main)', borderRadius: '10px', border: '1px dashed var(--border-color)' }}>
              <CalendarClock size={32} color="var(--text-muted)" style={{ marginBottom: '0.75rem', opacity: 0.5 }} />
              <p style={{ marginBottom: '1rem' }}>No tienes citas próximas programadas.</p>
              <Link to="/cliente/pedir-cita" className="btn btn-primary">Agendar Ahora</Link>
            </div>
          )}
        </div>

        {/* Tarjeta de Resumen de Vehículos */}
        <div className="card" style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
           <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <h2 style={{ fontSize: '1.1rem', display: 'flex', alignItems: 'center', gap: '0.5rem', margin: 0 }}>
              <Car size={20} color="var(--secondary)"/> Mi Garaje
            </h2>
            <Link to="/cliente/mis-vehiculos" className="btn btn-outline" style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.72rem', padding: '0.35rem 0.85rem' }}>
               Ver todos <ArrowRight size={14}/>
            </Link>
          </div>

          {vehiculos.length > 0 ? (
             <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
               {vehiculos.slice(0, 3).map(veh => (
                 <div key={veh.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem', border: '1px solid var(--border-color)', borderRadius: '10px', background: 'var(--bg-main)', transition: 'border-color 0.2s' }}>
                    <div>
                      <h4 style={{ margin: 0, fontSize: '0.95rem', color: 'var(--text-main)' }}>{veh.marca} {veh.modelo}</h4>
                      <p style={{ margin: 0, fontSize: '0.8rem', color: 'var(--text-muted)' }}>Año: {veh.anio}</p>
                    </div>
                    <span style={{ fontWeight: 700, color: 'var(--text-main)', background: 'rgba(255,255,255,0.05)', padding: '4px 10px', borderRadius: '6px', letterSpacing: '1px', fontSize: '0.8rem', border: '1px solid rgba(255,255,255,0.1)', fontFamily: 'monospace' }}>
                      {veh.matricula}
                    </span>
                 </div>
               ))}
             </div>
          ) : (
             <div style={{ padding: '2rem 1rem', textAlign: 'center', background: 'var(--bg-main)', borderRadius: '10px', border: '1px dashed var(--border-color)' }}>
              <Car size={32} color="var(--text-muted)" style={{ marginBottom: '0.75rem', opacity: 0.5 }} />
              <p style={{ marginBottom: '1rem' }}>Aún no has registrado ningún vehículo.</p>
              <Link to="/cliente/mis-vehiculos" className="btn btn-primary">Registrar Vehículo</Link>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ClientePanel;

// frontend-web-new/src/app/features/cliente/components/cliente-panel/cliente-panel.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { RouterModule } from '@angular/router';
import { forkJoin } from 'rxjs';
import { environment } from '../../../../../environments/environment';
import { PageHeaderComponent } from '../../../../shared/components/page-header/page-header.component';
import { LocationSectionComponent } from '../../../../shared/components/location-section/location-section.component';
import { ContactSectionComponent } from '../../../../shared/components/contact-section/contact-section.component';
import { AuthService } from '../../../../core/services/auth.service';
import { CalendarClock, Car, ArrowRight, LucideAngularModule } from 'lucide-angular';

@Component({
  selector: 'app-cliente-panel',
  standalone: true,
  imports: [CommonModule, RouterModule, PageHeaderComponent, LocationSectionComponent, ContactSectionComponent, LucideAngularModule],
  templateUrl: './cliente-panel.component.html'
})
export class ClientePanelComponent implements OnInit {
  private http = inject(HttpClient);
  private authService = inject(AuthService);

  user = this.authService.getCurrentUserValue();
  citas: any[] = [];
  vehiculos: any[] = [];
  loading = true;

  readonly CalendarClock = CalendarClock;
  readonly Car = Car;
  readonly ArrowRight = ArrowRight;

  ngOnInit() {
    forkJoin({
      citas: this.http.get<any[]>(`${environment.apiUrl}/cliente/citas`),
      vehiculos: this.http.get<any[]>(`${environment.apiUrl}/cliente/vehiculos`)
    }).subscribe({
      next: (res) => {
        this.citas = res.citas;
        this.vehiculos = res.vehiculos;
        this.loading = false;
      },
      error: () => this.loading = false
    });
  }

  get proximasCitas() {
    return this.citas.filter(c => c.estado === 'PENDIENTE' || c.estado === 'EN_CURSO');
  }
}

<div *ngIf="loading" style="padding: 2rem; color: var(--text-muted);">Cargando panel...</div>

<div *ngIf="!loading">
  <app-page-header title="Hola, {{ user?.nombreCompleto }} 👋" subtitle="Bienvenido a tu panel de control. Gestiona tu garaje y tus próximas visitas."></app-page-header>

  <div class="grid-2">
    <!-- Tarjeta de Próxima Cita -->
    <div class="card" style="display: flex; flex-direction: column; gap: 1rem;">
      <div style="display: flex; justify-content: space-between; align-items: center;">
        <h2 style="font-size: 1.1rem; display: flex; align-items: center; gap: 0.5rem; margin: 0;">
          <lucide-icon [img]="CalendarClock" [size]="20" style="color: var(--primary)"></lucide-icon> Próximas Citas
        </h2>
        <a routerLink="/cliente/pedir-cita" class="btn btn-outline" style="font-size: 0.72rem; padding: 0.35rem 0.85rem;">+ Nueva Cita</a>
      </div>

      <div *ngIf="proximasCitas.length > 0; else noCitas" style="display: flex; flex-direction: column; gap: 0.75rem;">
        <div *ngFor="let cita of proximasCitas.slice(0, 3)" style="padding: 1rem; border: 1px solid var(--border-color); border-radius: 10px; background: var(--bg-main); transition: border-color 0.2s;">
          <div style="display: flex; justify-content: space-between; margin-bottom: 0.35rem;">
            <strong style="font-size: 0.9rem;">{{ cita.fechaHora | date:'short' }}</strong>
            <span class="badge {{ cita.estado }}">{{ cita.estado.replace('_', ' ') }}</span>
          </div>
          <p style="margin: 0; font-size: 0.85rem; color: var(--text-muted);">
            {{ cita.servicio?.nombre }} — {{ cita.vehiculo?.marca }} {{ cita.vehiculo?.modelo }} ({{ cita.vehiculo?.matricula }})
          </p>
        </div>
      </div>
      <ng-template #noCitas>
        <div style="padding: 2rem 1rem; text-align: center; background: var(--bg-main); border-radius: 10px; border: 1px dashed var(--border-color);">
          <lucide-icon [img]="CalendarClock" [size]="32" style="color: var(--text-muted); margin-bottom: 0.75rem; opacity: 0.5;"></lucide-icon>
          <p style="margin-bottom: 1rem;">No tienes citas próximas programadas.</p>
          <a routerLink="/cliente/pedir-cita" class="btn btn-primary">Agendar Ahora</a>
        </div>
      </ng-template>
    </div>

    <!-- Tarjeta de Resumen de Vehículos -->
    <div class="card" style="display: flex; flex-direction: column; gap: 1rem;">
      <div style="display: flex; justify-content: space-between; align-items: center;">
        <h2 style="font-size: 1.1rem; display: flex; align-items: center; gap: 0.5rem; margin: 0;">
          <lucide-icon [img]="Car" [size]="20" style="color: var(--secondary)"></lucide-icon> Mi Garaje
        </h2>
        <a routerLink="/cliente/mis-vehiculos" class="btn btn-outline" style="display: flex; align-items: center; gap: 4px; font-size: 0.72rem; padding: 0.35rem 0.85rem;">
          Ver todos <lucide-icon [img]="ArrowRight" [size]="14"></lucide-icon>
        </a>
      </div>

      <div *ngIf="vehiculos.length > 0; else noVehiculos" style="display: flex; flex-direction: column; gap: 0.75rem;">
        <div *ngFor="let veh of vehiculos.slice(0, 3)" style="display: flex; justify-content: space-between; align-items: center; padding: 1rem; border: 1px solid var(--border-color); border-radius: 10px; background: var(--bg-main); transition: border-color 0.2s;">
          <div>
            <h4 style="margin: 0; font-size: 0.95rem; color: var(--text-main);">{{ veh.marca }} {{ veh.modelo }}</h4>
            <p style="margin: 0; font-size: 0.8rem; color: var(--text-muted);">Año: {{ veh.anio }}</p>
          </div>
          <span style="font-weight: 700; color: var(--text-main); background: rgba(255,255,255,0.05); padding: 4px 10px; border-radius: 6px; letter-spacing: 1px; font-size: 0.8rem; border: 1px solid rgba(255,255,255,0.1); font-family: monospace;">
            {{ veh.matricula }}
          </span>
        </div>
      </div>
      <ng-template #noVehiculos>
        <div style="padding: 2rem 1rem; text-align: center; background: var(--bg-main); border-radius: 10px; border: 1px dashed var(--border-color);">
          <lucide-icon [img]="Car" [size]="32" style="color: var(--text-muted); margin-bottom: 0.75rem; opacity: 0.5;"></lucide-icon>
          <p style="margin-bottom: 1rem;">Aún no has registrado ningún vehículo.</p>
          <a routerLink="/cliente/mis-vehiculos" class="btn btn-primary">Registrar Vehículo</a>
        </div>
      </ng-template>
    </div>
  </div>

  <app-location-section id="ubicacion"></app-location-section>
  <app-contact-section id="contacto"></app-contact-section>
</div>
