// frontend-web/src/pages/cliente/PedirCita.jsx
import { useState, useEffect } from 'react';
import api from '../../api/axiosConfig';
import { CalendarPlus, CheckCircle2, Clock } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import PageHeader from '../../components/PageHeader/PageHeader';

const PedirCita = () => {
  const [vehiculos, setVehiculos] = useState([]);
  const [servicios, setServicios] = useState([]);
  const [loading, setLoading] = useState(true);
  
  const [selectedVehiculo, setSelectedVehiculo] = useState('');
  const [selectedServicio, setSelectedServicio] = useState('');
  
  const [fechaSeleccionada, setFechaSeleccionada] = useState('');
  const [horasDisponibles, setHorasDisponibles] = useState([]);
  const [horaSeleccionada, setHoraSeleccionada] = useState('');
  const [cargandoHoras, setCargandoHoras] = useState(false);
  
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState('');
  const navigate = useNavigate();

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [vehiculosRes, serviciosRes] = await Promise.all([
          api.get('/cliente/vehiculos'),
          api.get('/cliente/servicios')
        ]);
        setVehiculos(vehiculosRes.data);
        setServicios(serviciosRes.data);
      } catch (err) {
        console.error(err);
        setError("Error al cargar los datos del formulario.");
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  useEffect(() => {
    setHoraSeleccionada('');
    setHorasDisponibles([]);
    
    if (fechaSeleccionada) {
      const fetchHoras = async () => {
        setCargandoHoras(true);
        try {
          const res = await api.get(`/cliente/citas/disponibilidad?fecha=${fechaSeleccionada}`);
          setHorasDisponibles(res.data);
        } catch (err) {
          console.error("Error obteniendo horas:", err);
          setError("No se pudieron cargar las horas disponibles para ese día.");
        } finally {
          setCargandoHoras(false);
        }
      };
      fetchHoras();
    }
  }, [fechaSeleccionada]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    
    if (!selectedVehiculo || !selectedServicio || !fechaSeleccionada || !horaSeleccionada) {
      setError('Por favor, completa todos los campos.');
      return;
    }

    try {
      const formParams = new URLSearchParams();
      formParams.append('vehiculoId', selectedVehiculo);
      formParams.append('servicioId', selectedServicio);
      const fechaHoraISO = `${fechaSeleccionada}T${horaSeleccionada}:00`;
      formParams.append('fechaHora', fechaHoraISO);

      await api.post('/cliente/citas', formParams);
      
      setSuccess(true);
      setTimeout(() => {
        navigate('/cliente/panel');
      }, 2500);

    } catch (err) {
      console.error(err);
      setError(err.response?.data || "Ocurrió un error al agendar la cita.");
    }
  };

  if (loading) return <div style={{ padding: '2rem', color: 'var(--text-muted)' }}>Cargando formulario...</div>;

  if (success) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '60vh', gap: '1rem' }}>
        <div style={{ width: '80px', height: '80px', borderRadius: '50%', background: 'rgba(16,185,129,0.1)', border: '2px solid rgba(16,185,129,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: '0 0 30px rgba(16,185,129,0.2)' }}>
          <CheckCircle2 size={44} color="#6ee7b7" />
        </div>
        <h2 style={{ fontSize: '1.75rem', margin: 0 }}>¡Cita Solicitada con Éxito!</h2>
        <p style={{ color: 'var(--text-muted)' }}>Redirigiendo a tu panel...</p>
      </div>
    );
  }

  const minDate = new Date().toISOString().split('T')[0];

  return (
    <div style={{ maxWidth: '640px', margin: '0 auto' }}>
      <PageHeader
        icon={<CalendarPlus size={26} color="var(--primary)" />}
        title="Agendar Nueva Cita"
        subtitle="Selecciona tu vehículo, el servicio que necesitas y la fecha deseada."
      />

      <div className="card">
        {error && (
          <div style={{ padding: '0.85rem 1rem', background: 'rgba(239, 68, 68, 0.1)', color: 'var(--danger)', borderRadius: '10px', marginBottom: '1.5rem', fontWeight: 500, border: '1px solid rgba(239, 68, 68, 0.3)', fontSize: '0.9rem' }}>
            {error}
          </div>
        )}
        
        <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          
          <div className="form-group">
            <label className="form-label">Vehículo</label>
            {vehiculos.length === 0 ? (
              <p style={{ color: 'var(--warning)', fontSize: '0.875rem', padding: '0.75rem', background: 'rgba(245,158,11,0.08)', borderRadius: '8px', border: '1px solid rgba(245,158,11,0.2)', margin: 0 }}>
                ⚠️ Debes registrar un vehículo en tu garaje antes de pedir una cita.
              </p>
            ) : (
              <select className="form-select" value={selectedVehiculo} onChange={(e) => setSelectedVehiculo(e.target.value)}>
                <option value="">-- Selecciona un Vehículo --</option>
                {vehiculos.map(v => (
                  <option key={v.id} value={v.id}>{v.marca} {v.modelo} ({v.matricula})</option>
                ))}
              </select>
            )}
          </div>

          <div className="form-group">
            <label className="form-label">Tipo de Servicio</label>
            <select className="form-select" value={selectedServicio} onChange={(e) => setSelectedServicio(e.target.value)}>
              <option value="">-- Selecciona el Servicio --</option>
              {servicios.map(s => (
                <option key={s.id} value={s.id}>
                  {s.nombre} — {s.precioBase || s.precio}€ · {s.duracionMinutos ? `${s.duracionMinutos} min` : 'Duración variable'}
                </option>
              ))}
            </select>
          </div>

          <div className="form-group">
            <label className="form-label">Fecha de Visita</label>
            <input 
              type="date" 
              className="form-input" 
              value={fechaSeleccionada} 
              onChange={(e) => setFechaSeleccionada(e.target.value)}
              min={minDate} 
            />
          </div>

          {fechaSeleccionada && (
            <div className="form-group">
              <label className="form-label">Hora Disponible</label>
              {cargandoHoras ? (
                 <p style={{ color: 'var(--text-muted)', fontSize: '0.875rem' }}>Buscando huecos libres...</p>
              ) : horasDisponibles.length > 0 ? (
                 <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.6rem' }}>
                    {horasDisponibles.map(hora => (
                       <button
                         key={hora}
                         type="button"
                         onClick={() => setHoraSeleccionada(hora)}
                         style={{
                            padding: '0.5rem 1rem',
                            border: `2px solid ${horaSeleccionada === hora ? 'var(--primary)' : 'var(--border-color)'}`,
                            borderRadius: '10px',
                            background: horaSeleccionada === hora ? 'rgba(225,29,72,0.12)' : 'var(--bg-main)',
                            color: horaSeleccionada === hora ? 'var(--primary)' : 'var(--text-main)',
                            fontWeight: horaSeleccionada === hora ? 700 : 400,
                            cursor: 'pointer',
                            display: 'flex',
                            alignItems: 'center',
                            gap: '0.4rem',
                            transition: 'all 0.2s',
                            fontSize: '0.9rem',
                            boxShadow: horaSeleccionada === hora ? 'var(--shadow-glow-red)' : 'none'
                         }}
                       >
                         <Clock size={15} /> {hora}
                       </button>
                    ))}
                 </div>
              ) : (
                 <p style={{ color: 'var(--danger)', fontSize: '0.875rem', padding: '0.75rem', background: 'rgba(239, 68, 68, 0.1)', border: '1px solid rgba(239, 68, 68, 0.3)', borderRadius: '8px', margin: 0 }}>
                    No hay horas disponibles para este día (Completo o Cerrado).
                 </p>
              )}
            </div>
          )}

          <div style={{ marginTop: '0.5rem', display: 'flex', justifyContent: 'flex-end' }}>
             <button type="submit" className="btn btn-primary" style={{ padding: '0.85rem 2.5rem', fontSize: '1rem' }} disabled={vehiculos.length === 0 || !horaSeleccionada}>
                Confirmar Cita
             </button>
          </div>

        </form>
      </div>
    </div>
  );
};

export default PedirCita;

// frontend-web-new/src/app/features/cliente/components/pedir-cita/pedir-cita.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { forkJoin } from 'rxjs';
import { environment } from '../../../../../environments/environment';
import { PageHeaderComponent } from '../../../../shared/components/page-header/page-header.component';
import { CalendarPlus, CheckCircle2, Clock, LucideAngularModule } from 'lucide-angular';

@Component({
  selector: 'app-pedir-cita',
  standalone: true,
  imports: [CommonModule, FormsModule, PageHeaderComponent, LucideAngularModule],
  templateUrl: './pedir-cita.component.html'
})
export class PedirCitaComponent implements OnInit {
  private http = inject(HttpClient);
  private router = inject(Router);

  vehiculos: any[] = [];
  servicios: any[] = [];
  loading = true;
  
  selectedVehiculo = '';
  selectedServicio = '';
  
  fechaSeleccionada = '';
  horasDisponibles: string[] = [];
  horaSeleccionada = '';
  cargandoHoras = false;
  
  success = false;
  error = '';

  readonly CalendarPlus = CalendarPlus;
  readonly CheckCircle2 = CheckCircle2;
  readonly Clock = Clock;
  
  minDate = new Date().toISOString().split('T')[0];

  ngOnInit() {
    forkJoin({
      vehiculos: this.http.get<any[]>(`${environment.apiUrl}/cliente/vehiculos`),
      servicios: this.http.get<any[]>(`${environment.apiUrl}/cliente/servicios`)
    }).subscribe({
      next: (res) => {
        this.vehiculos = res.vehiculos;
        this.servicios = res.servicios;
        this.loading = false;
      },
      error: () => {
        this.error = "Error al cargar los datos del formulario.";
        this.loading = false;
      }
    });
  }

  onFechaChange() {
    this.horaSeleccionada = '';
    this.horasDisponibles = [];
    
    if (this.fechaSeleccionada) {
      this.cargandoHoras = true;
      this.http.get<string[]>(`${environment.apiUrl}/cliente/citas/disponibilidad?fecha=${this.fechaSeleccionada}`).subscribe({
        next: (res) => {
          this.horasDisponibles = res;
          this.cargandoHoras = false;
        },
        error: () => {
          this.error = "No se pudieron cargar las horas disponibles para ese día.";
          this.cargandoHoras = false;
        }
      });
    }
  }

  handleSubmit() {
    this.error = '';
    
    if (!this.selectedVehiculo || !this.selectedServicio || !this.fechaSeleccionada || !this.horaSeleccionada) {
      this.error = 'Por favor, completa todos los campos.';
      return;
    }

    const formParams = new URLSearchParams();
    formParams.append('vehiculoId', this.selectedVehiculo);
    formParams.append('servicioId', this.selectedServicio);
    const fechaHoraISO = `${this.fechaSeleccionada}T${this.horaSeleccionada}:00`;
    formParams.append('fechaHora', fechaHoraISO);

    this.http.post(`${environment.apiUrl}/cliente/citas`, formParams.toString(), {
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' }
    }).subscribe({
      next: () => {
        this.success = true;
        setTimeout(() => {
          this.router.navigate(['/cliente/panel']);
        }, 2500);
      },
      error: (err) => {
        this.error = err.error || "Ocurrió un error al agendar la cita.";
      }
    });
  }
}

<div *ngIf="loading" style="padding: 2rem; color: var(--text-muted);">Cargando formulario...</div>

<div *ngIf="success" style="display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 60vh; gap: 1rem;">
  <div style="width: 80px; height: 80px; border-radius: 50%; background: rgba(16,185,129,0.1); border: 2px solid rgba(16,185,129,0.4); display: flex; align-items: center; justify-content: center; box-shadow: 0 0 30px rgba(16,185,129,0.2);">
    <lucide-icon [img]="CheckCircle2" [size]="44" style="color: #6ee7b7;"></lucide-icon>
  </div>
  <h2 style="font-size: 1.75rem; margin: 0;">¡Cita Solicitada con Éxito!</h2>
  <p style="color: var(--text-muted);">Redirigiendo a tu panel...</p>
</div>

<div *ngIf="!loading && !success" style="max-width: 640px; margin: 0 auto;">
  <app-page-header title="Agendar Nueva Cita" subtitle="Selecciona tu vehículo, el servicio que necesitas y la fecha deseada."></app-page-header>

  <div class="card">
    <div *ngIf="error" style="padding: 0.85rem 1rem; background: rgba(239, 68, 68, 0.1); color: var(--danger); border-radius: 10px; margin-bottom: 1.5rem; font-weight: 500; border: 1px solid rgba(239, 68, 68, 0.3); font-size: 0.9rem;">
      {{ error }}
    </div>
    
    <form (ngSubmit)="handleSubmit()" style="display: flex; flex-direction: column; gap: 1.5rem;">
      
      <div class="form-group">
        <label class="form-label">Vehículo</label>
        <p *ngIf="vehiculos.length === 0" style="color: var(--warning); font-size: 0.875rem; padding: 0.75rem; background: rgba(245,158,11,0.08); border-radius: 8px; border: 1px solid rgba(245,158,11,0.2); margin: 0;">
          ⚠️ Debes registrar un vehículo en tu garaje antes de pedir una cita.
        </p>
        <select *ngIf="vehiculos.length > 0" class="form-select" name="selectedVehiculo" [(ngModel)]="selectedVehiculo">
          <option value="">-- Selecciona un Vehículo --</option>
          <option *ngFor="let v of vehiculos" [value]="v.id">{{ v.marca }} {{ v.modelo }} ({{ v.matricula }})</option>
        </select>
      </div>

      <div class="form-group">
        <label class="form-label">Tipo de Servicio</label>
        <select class="form-select" name="selectedServicio" [(ngModel)]="selectedServicio">
          <option value="">-- Selecciona el Servicio --</option>
          <option *ngFor="let s of servicios" [value]="s.id">
            {{ s.nombre }} — {{ s.precioBase || s.precio }}€ · {{ s.duracionMinutos ? s.duracionMinutos + ' min' : 'Duración variable' }}
          </option>
        </select>
      </div>

      <div class="form-group">
        <label class="form-label">Fecha de Visita</label>
        <input type="date" class="form-input" name="fechaSeleccionada" [(ngModel)]="fechaSeleccionada" (change)="onFechaChange()" [min]="minDate" />
      </div>

      <div *ngIf="fechaSeleccionada" class="form-group">
        <label class="form-label">Hora Disponible</label>
        <p *ngIf="cargandoHoras" style="color: var(--text-muted); font-size: 0.875rem;">Buscando huecos libres...</p>
        <div *ngIf="!cargandoHoras && horasDisponibles.length > 0" style="display: flex; flex-wrap: wrap; gap: 0.6rem;">
          <button *ngFor="let hora of horasDisponibles" type="button" (click)="horaSeleccionada = hora" [ngStyle]="{'border': horaSeleccionada === hora ? '2px solid var(--primary)' : '2px solid var(--border-color)', 'background': horaSeleccionada === hora ? 'rgba(225,29,72,0.12)' : 'var(--bg-main)', 'color': horaSeleccionada === hora ? 'var(--primary)' : 'var(--text-main)', 'font-weight': horaSeleccionada === hora ? 700 : 400, 'box-shadow': horaSeleccionada === hora ? 'var(--shadow-glow-red)' : 'none'}" style="padding: 0.5rem 1rem; border-radius: 10px; cursor: pointer; display: flex; align-items: center; gap: 0.4rem; transition: all 0.2s; font-size: 0.9rem;">
            <lucide-icon [img]="Clock" [size]="15"></lucide-icon> {{ hora }}
          </button>
        </div>
        <p *ngIf="!cargandoHoras && horasDisponibles.length === 0" style="color: var(--danger); font-size: 0.875rem; padding: 0.75rem; background: rgba(239, 68, 68, 0.1); border: 1px solid rgba(239, 68, 68, 0.3); border-radius: 8px; margin: 0;">
          No hay horas disponibles para este día (Completo o Cerrado).
        </p>
      </div>

      <div style="margin-top: 0.5rem; display: flex; justify-content: flex-end;">
        <button type="submit" class="btn btn-primary" style="padding: 0.85rem 2.5rem; font-size: 1rem;" [disabled]="vehiculos.length === 0 || !horaSeleccionada">
          Confirmar Cita
        </button>
      </div>

    </form>
  </div>
</div>
