// frontend-web/src/pages/admin/HistorialCitas.jsx
import { useState, useEffect } from 'react';
import api from '../../api/axiosConfig';
import { History, Search } from 'lucide-react';
import PageHeader from '../../components/PageHeader/PageHeader';
import { SkeletonList } from '../../components/Skeleton/Skeleton';

const HistorialCitas = () => {
  const [citas, setCitas] = useState([]);
  const [loading, setLoading] = useState(true);
  const [busqueda, setBusqueda] = useState('');
  const [filtroEstado, setFiltroEstado] = useState('todas');

  useEffect(() => {
    api.get('/admin/citas')
      .then(res => setCitas(res.data))
      .finally(() => setLoading(false));
  }, []);

  const pasadas = citas.filter(c => ['FINALIZADA', 'CANCELADA'].includes(c.estado));

  const filtradas = pasadas.filter(c => {
    const matchEstado = filtroEstado === 'todas' || c.estado === filtroEstado;
    const termino = busqueda.toLowerCase();
    const matchBusqueda = !termino ||
      c.cliente?.nombreCompleto?.toLowerCase().includes(termino) ||
      c.vehiculo?.matricula?.toLowerCase().includes(termino) ||
      c.servicio?.nombre?.toLowerCase().includes(termino);
    return matchEstado && matchBusqueda;
  });

  const BADGE = {
    FINALIZADA: { bg: 'rgba(16,185,129,0.1)', border: 'rgba(16,185,129,0.3)', color: '#6ee7b7' },
    CANCELADA:  { bg: 'rgba(239,68,68,0.1)',  border: 'rgba(239,68,68,0.3)',  color: '#fca5a5' },
  };

  return (
    <div>
      <PageHeader
        icon={<History size={26} color="var(--primary)" />}
        title="Historial de Citas"
        subtitle="Registro de todas las citas finalizadas y canceladas del taller."
      />

      {/* Filtros */}
      <div style={{ display: 'flex', gap: '1rem', marginBottom: '1.5rem', flexWrap: 'wrap' }}>
        <div style={{ position: 'relative', flex: '1', minWidth: '220px' }}>
          <Search size={16} style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)', pointerEvents: 'none' }} />
          <input
            type="text"
            className="form-input"
            placeholder="Buscar por cliente, matrícula o servicio..."
            value={busqueda}
            onChange={e => setBusqueda(e.target.value)}
            style={{ paddingLeft: '2.3rem' }}
          />
        </div>
        <select className="form-select" value={filtroEstado} onChange={e => setFiltroEstado(e.target.value)} style={{ width: 'auto', minWidth: '160px' }}>
          <option value="todas">Todos los estados</option>
          <option value="FINALIZADA">Finalizadas</option>
          <option value="CANCELADA">Canceladas</option>
        </select>
      </div>

      {loading ? <SkeletonList rows={5} /> : filtradas.length === 0 ? (
        <div className="card" style={{ textAlign: 'center', padding: '3rem' }}>
          <History size={48} color="var(--text-muted)" style={{ margin: '0 auto 1rem', opacity: 0.4 }} />
          <p>No se encontraron citas con los filtros actuales.</p>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
          <p style={{ fontSize: '0.82rem', color: 'var(--text-muted)', marginBottom: '0.25rem' }}>{filtradas.length} cita{filtradas.length !== 1 ? 's' : ''} encontrada{filtradas.length !== 1 ? 's' : ''}</p>
          {filtradas.map(cita => {
            const b = BADGE[cita.estado] || BADGE.FINALIZADA;
            return (
              <div key={cita.id} style={{ display: 'flex', alignItems: 'center', gap: '1.25rem', padding: '1.1rem 1.25rem', background: 'var(--bg-card)', border: '1px solid var(--border-color)', borderRadius: '12px', flexWrap: 'wrap', transition: 'border-color 0.2s' }}>
                <div style={{ textAlign: 'center', background: 'var(--bg-main)', border: '1px solid var(--border-color)', padding: '0.6rem 0.85rem', borderRadius: '8px', flexShrink: 0, minWidth: '60px' }}>
                  <span style={{ display: 'block', fontSize: '1.25rem', fontWeight: 900, color: 'var(--primary)', lineHeight: 1 }}>{new Date(cita.fechaHora).getDate()}</span>
                  <span style={{ display: 'block', fontSize: '0.65rem', color: 'var(--text-muted)', textTransform: 'uppercase' }}>{new Date(cita.fechaHora).toLocaleString('es-ES', { month: 'short', year: '2-digit' })}</span>
                </div>
                <div style={{ flex: 1, minWidth: '180px' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.65rem', flexWrap: 'wrap', marginBottom: '0.25rem' }}>
                    <strong style={{ fontSize: '0.95rem' }}>{cita.cliente?.nombreCompleto || 'Desconocido'}</strong>
                    <span style={{ padding: '1px 8px', borderRadius: '10px', background: b.bg, border: `1px solid ${b.border}`, color: b.color, fontSize: '0.7rem', fontWeight: 700 }}>
                      {cita.estado}
                    </span>
                  </div>
                  <p style={{ margin: 0, fontSize: '0.82rem', color: 'var(--text-muted)' }}>
                    🔧 {cita.servicio?.nombre} — 🚗 {cita.vehiculo?.marca} {cita.vehiculo?.modelo}
                    <span style={{ fontFamily: 'monospace', fontSize: '0.78rem', marginLeft: '5px', background: 'rgba(255,255,255,0.04)', padding: '1px 5px', borderRadius: '4px', border: '1px solid var(--border-color)' }}>{cita.vehiculo?.matricula}</span>
                  </p>
                </div>
                <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', flexShrink: 0 }}>
                  {new Date(cita.fechaHora).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default HistorialCitas;

// frontend-web-new/src/app/features/admin/components/historial-citas/historial-citas.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { environment } from '../../../../../environments/environment';
import { PageHeaderComponent } from '../../../../shared/components/page-header/page-header.component';
import { History, Search, LucideAngularModule } from 'lucide-angular';

@Component({
  selector: 'app-historial-citas',
  standalone: true,
  imports: [CommonModule, FormsModule, PageHeaderComponent, LucideAngularModule],
  templateUrl: './historial-citas.component.html'
})
export class HistorialCitasComponent implements OnInit {
  private http = inject(HttpClient);

  citas: any[] = [];
  loading = true;
  busqueda = '';
  filtroEstado = 'todas';

  readonly HistoryIcon = History;
  readonly Search = Search;

  BADGE: any = {
    FINALIZADA: { bg: 'rgba(16,185,129,0.1)', border: 'rgba(16,185,129,0.3)', color: '#6ee7b7' },
    CANCELADA:  { bg: 'rgba(239,68,68,0.1)',  border: 'rgba(239,68,68,0.3)',  color: '#fca5a5' },
  };

  ngOnInit() {
    this.http.get<any[]>(`${environment.apiUrl}/admin/citas`).subscribe({
      next: (res) => {
        this.citas = res || [];
        this.loading = false;
      },
      error: (err) => {
        console.error('Error cargando historial:', err);
        this.loading = false;
      }
    });
  }

  get filtradas() {
    const pasadas = this.citas.filter(c => ['FINALIZADA', 'CANCELADA'].includes(c.estado));
    return pasadas.filter(c => {
      const matchEstado = this.filtroEstado === 'todas' || c.estado === this.filtroEstado;
      const termino = this.busqueda.toLowerCase();
      const matchBusqueda = !termino ||
        c.cliente?.nombreCompleto?.toLowerCase().includes(termino) ||
        c.vehiculo?.matricula?.toLowerCase().includes(termino) ||
        c.servicio?.nombre?.toLowerCase().includes(termino);
      return matchEstado && matchBusqueda;
    });
  }
}

<div *ngIf="loading" style="padding: 2rem; color: var(--text-muted);">Cargando historial...</div>

<div *ngIf="!loading">
  <app-page-header title="Historial de Citas" subtitle="Registro de todas las citas finalizadas y canceladas del taller."></app-page-header>

  <!-- Filtros -->
  <div style="display: flex; gap: 1rem; margin-bottom: 1.5rem; flex-wrap: wrap;">
    <div style="position: relative; flex: 1; min-width: 220px;">
      <lucide-icon [img]="Search" [size]="16" style="position: absolute; left: 12px; top: 50%; transform: translateY(-50%); color: var(--text-muted); pointer-events: none;"></lucide-icon>
      <input type="text" class="form-input" placeholder="Buscar por cliente, matrícula o servicio..." [(ngModel)]="busqueda" style="padding-left: 2.3rem;" />
    </div>
    <select class="form-select" [(ngModel)]="filtroEstado" style="width: auto; min-width: 160px;">
      <option value="todas">Todos los estados</option>
      <option value="FINALIZADA">Finalizadas</option>
      <option value="CANCELADA">Canceladas</option>
    </select>
  </div>

  <div *ngIf="filtradas.length === 0; else list" class="card" style="text-align: center; padding: 3rem;">
    <lucide-icon [img]="HistoryIcon" [size]="48" style="color: var(--text-muted); margin: 0 auto 1rem; opacity: 0.4;"></lucide-icon>
    <p>No se encontraron citas con los filtros actuales.</p>
  </div>

  <ng-template #list>
    <div style="display: flex; flex-direction: column; gap: 0.85rem;">
      <p style="font-size: 0.82rem; color: var(--text-muted); margin-bottom: 0.25rem;">
        {{ filtradas.length }} cita{{ filtradas.length !== 1 ? 's' : '' }} encontrada{{ filtradas.length !== 1 ? 's' : '' }}
      </p>
      <div *ngFor="let cita of filtradas" style="display: flex; align-items: center; gap: 1.25rem; padding: 1.1rem 1.25rem; background: var(--bg-card); border: 1px solid var(--border-color); border-radius: 12px; flex-wrap: wrap; transition: border-color 0.2s;">
        <div style="text-align: center; background: var(--bg-main); border: 1px solid var(--border-color); padding: 0.6rem 0.85rem; border-radius: 8px; flex-shrink: 0; min-width: 60px;">
          <span style="display: block; font-size: 1.25rem; font-weight: 900; color: var(--primary); line-height: 1;">{{ cita.fechaHora | date:'d' }}</span>
          <span style="display: block; font-size: 0.65rem; color: var(--text-muted); text-transform: uppercase;">{{ cita.fechaHora | date:'MMM yy' }}</span>
        </div>
        <div style="flex: 1; min-width: 180px;">
          <div style="display: flex; align-items: center; gap: 0.65rem; flex-wrap: wrap; margin-bottom: 0.25rem;">
            <strong style="font-size: 0.95rem;">{{ cita.cliente?.nombreCompleto || 'Desconocido' }}</strong>
            <span style="padding: 1px 8px; border-radius: 10px; font-size: 0.7rem; font-weight: 700;" [ngStyle]="{'background': (BADGE[cita.estado] || BADGE.FINALIZADA).bg, 'border': '1px solid ' + (BADGE[cita.estado] || BADGE.FINALIZADA).border, 'color': (BADGE[cita.estado] || BADGE.FINALIZADA).color}">
              {{ cita.estado }}
            </span>
          </div>
          <p style="margin: 0; font-size: 0.82rem; color: var(--text-muted);">
            🔧 {{ cita.servicio?.nombre }} — 🚗 {{ cita.vehiculo?.marca }} {{ cita.vehiculo?.modelo }}
            <span style="font-family: monospace; font-size: 0.78rem; margin-left: 5px; background: rgba(255,255,255,0.04); padding: 1px 5px; border-radius: 4px; border: 1px solid var(--border-color);">{{ cita.vehiculo?.matricula }}</span>
          </p>
        </div>
        <div style="font-size: 0.8rem; color: var(--text-muted); flex-shrink: 0;">
          {{ cita.fechaHora | date:'h:mm a' }}
        </div>
      </div>
    </div>
  </ng-template>
</div>
